# Generated by Django 4.0 on 2022-01-07 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customusers_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 11, 42, 26, 499251)),
        ),
    ]
