# Generated by Django 3.1.4 on 2022-01-09 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_customusers_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 12, 36, 41, 456201)),
        ),
    ]
