# Generated by Django 4.0 on 2022-01-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_shoes_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes_image',
            name='images',
            field=models.ImageField(upload_to='images/shoes/<django.db.models.query_utils.DeferredAttribute object at 0x000001630BDAB640>||<django.db.models.query_utils.DeferredAttribute object at 0x000001630BDAB6A0>'),
        ),
    ]
