# Generated by Django 4.0 on 2022-01-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_shoes_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='brand',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes_image',
            name='images',
            field=models.ImageField(upload_to='images/shoes/<django.db.models.query_utils.DeferredAttribute object at 0x0000028BD9E5A700>||<django.db.models.query_utils.DeferredAttribute object at 0x0000028BD9E5A7C0>'),
        ),
    ]
