# Generated by Django 4.0 on 2022-01-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_shoe_brand_alter_shoes_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='images',
        ),
        migrations.AlterField(
            model_name='shoes_image',
            name='images',
            field=models.ImageField(upload_to='images/shoes/<django.db.models.query_utils.DeferredAttribute object at 0x000002CD5284A6D0>||<django.db.models.query_utils.DeferredAttribute object at 0x000002CD5284A790>'),
        ),
    ]
