# Generated by Django 4.0 on 2022-01-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_shoes_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes_image',
            name='images',
            field=models.ImageField(upload_to='static/images/shoes/shoes_DB/'),
        ),
    ]
