# Generated by Django 4.0 on 2022-01-07 11:02

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_shoes_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='images',
            field=models.FileField(default='', upload_to=products.models.file_path),
            preserve_default=False,
        ),
    ]
